dependencies:
- name: baba
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: boubou
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: rom10
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: rom8
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: rom9
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: test-build-logs
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: to-import-2
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: to-import-3
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
